//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Final_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Propietario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Propietario()
        {
            this.Tb_Auto = new HashSet<Tb_Auto>();
        }
    
        public string Cod_Propietario { get; set; }
        public string Nom_Propietario { get; set; }
        public string Ape_Propietario { get; set; }
        public string Dir_Propietario { get; set; }
        public string DNI_Propietario { get; set; }
        public string Cod_Distrito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Auto> Tb_Auto { get; set; }
        public virtual Tb_Distrito Tb_Distrito { get; set; }
    }
}
