//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Final_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Papeleta
    {
        public string Num_Papeleta { get; set; }
        public Nullable<System.DateTime> Fec_Papeleta { get; set; }
        public string Cod_Infraccion { get; set; }
        public string Num_Placa { get; set; }
        public string Est_Papeleta { get; set; }
        public string Cod_Agente { get; set; }
    
        public virtual Tb_Agente Tb_Agente { get; set; }
        public virtual Tb_Auto Tb_Auto { get; set; }
        public virtual Tb_Infraccion Tb_Infraccion { get; set; }
    }
}
